--DROP TABLE AREA 
DROP TABLE Reviews;
DROP TABLE Project_Orders;
DROP TABLE Warehouse_Products;
DROP TABLE Stores;
DROP TABLE Warehouse;
DROP TABLE Products;
DROP TABLE Project_Customers;
DROP TABLE Cities;